version: "2"
services:
  virtuoso:
    image: niklas88/virtuoso-freebase
    build:
      context: virtuoso
    restart: unless-stopped
    expose:
      - "8999"
    ports:
      - "8999:8999"
    volumes:
      - ./virtuoso-db:/data
      - /nfs/datasets/freebase:/input
  varnish:
    image: niklas88/varnish-virtuoso
    build:
      context: varnish
    restart: unless-stopped
    depends_on:
      - virtuoso
    tmpfs:
      - /tmp
    expose:
      - "9000"
    ports:
      - "9000:9000"

