version: "2"
services:
  virtuoso:
    build:
      context: virtuoso
    restart: unless-stopped
    expose:
      - "8999"
    volumes:
      - ./virtuoso-db:/data
  varnish:
    build:
      context: varnish
    restart: unless-stopped
    depends_on:
      - virtuoso
    tmpfs:
      - /tmp
    ports:
      - "9000:9000"

